#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 22 14:18:39 2018

@author: thiago
"""

class Node():
    def __init__(self, name, vizinhos, distancia_vizinhos):
        self.name = name
        self.vizinhos = vizinhos
        self.distancia_vizinhos = distancia_vizinhos
        
    def getNeighbors(self):
        return self.vizinhos
    
    def getDistanceTo(self):
        return self.distancia_vizinhos
    
class Edges():
    def __init__(self, node1, node2):
        self.node1 = node1
        self.node2 = node2
        